name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Build site
      run: make build
      env:
        RDP_APP_KEY: ${{ secrets.RDP_APP_KEY }}
        RDP_USERNAME: ${{ secrets.RDP_USERNAME }}
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}

    - name: Upload release candidate
      uses: actions/upload-artifact@v3
      with:
        name: release-candidate
        path: ./docs/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download release candidate
      uses: actions/download-artifact@v3
      with:
        name: release-candidate
        path: ./docs/

    - id: configure-aws
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - id: upload-to-s3
      name: Upload documentation to Amazon S3
      uses: datadesk/delivery-deploy-action@v1
      with:
        bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
        base-path: refinitiv-data-python-cookbook/
        dir: ./docs/
        should-cache: false
        use-accelerate-endpoint: false
        public: true
