name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Build site
      run: make build
      env:
        RDP_APP_KEY: ${{ secrets.RDP_APP_KEY }}
        RDP_USERNAME: ${{ secrets.RDP_USERNAME }}
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}

    - name: Upload release candidate
      uses: actions/upload-artifact@v3
      with:
        name: release-candidate
        path: ./docs/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download release candidate
      uses: actions/download-artifact@v3
      with:
        name: release-candidate
        path: ./docs/

    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
        source_dir: docs/_build/
        destination_dir: refinitiv-data-python-cookbook
